### ISSUE TITLE
SSL certificate generation fails on brand-new container

### ISSUE THREAD

**Issue by trmckay** [jc21/nginx-proxy-manager#1000]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? Yes.
- Are you sure you're not using someone else's docker image? Yes.
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? Yes.

**Describe the bug**

I am running a brand-new instance of the latest container on a nearly stock install of Fedora 33 Server. When trying to create SSL certs I get the following error. 

```
Error: Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-1" --agree-tos --email "XXXXXXXXXXXXX" --preferred-challenges "dns,http" --domains "XXXXXXXXXXXX" 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
An unexpected error occurred:
The JWS was signed by a public key the server does not support :: sa.StorageAuthority.KeyBlocked timed out after 5001 ms
Please see the logfiles in /var/log/letsencrypt for more details.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

Looks like some sort of time-out? I'm really not sure.

**To Reproduce**
1. Pull/run/start the container.
2. Configure admin user.
3. Request new SSL certificate from LetsEncrypt.
4. See error.

**Expected behavior**
To request and subsequently receive an SSL cert.

**Operating System**
- Fedora 33 Server, x86_64: only installed Docker, and some user stuff like vim/tmux; no further configuration.

**Comment by trmckay** [comment]
Even though I could replicate the bug on new containers, it appears to have disappeared overnight. That leads me to guess it must have been a problem with my network that resolved itself. So, reader, if you are having this issue, take an 8-hour walk and maybe it will be better when you come back.
