### ISSUE TITLE
Problems in renewing certificates

### ISSUE THREAD

**Issue by trenetics** [jc21/nginx-proxy-manager#1018]
**Describe the bug**
Im having some trouble renewing certs with CloudFlare DNS Token. If i try to renew my certs manually it works, but takes a couple of minutes and the UI times out.

Auto renewals fail:

```
today at 21:26:56  `QueryBuilder#allowEager` method is deprecated. You should use `allowGraph` instead. `allowEager` method will be removed in 3.0
today at 21:26:56  `QueryBuilder#eager` method is deprecated. You should use the `withGraphFetched` method instead. `eager` method will be removed in 3.0
today at 21:26:56  QueryBuilder#omit is deprecated. This method will be removed in version 3.0
today at 21:27:24  [4/14/2021] [7:27:24 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  
today at 21:27:24  Challenge failed for domain te55er4ct.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-20) from /etc/letsencrypt/renewal/npm-20.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  Challenge failed for domain dr1v3.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-21) from /etc/letsencrypt/renewal/npm-21.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  Challenge failed for domain qu4n7um.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-22) from /etc/letsencrypt/renewal/npm-22.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  Challenge failed for domain tr3nw1k1.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-30) from /etc/letsencrypt/renewal/npm-30.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  Challenge failed for domain b1tw4rd3n.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-34) from /etc/letsencrypt/renewal/npm-34.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  Challenge failed for domain a1rs0n1c.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-35) from /etc/letsencrypt/renewal/npm-35.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  Challenge failed for domain s3nt1n3l.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-36) from /etc/letsencrypt/renewal/npm-36.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  Challenge failed for domain tr3nw1k1.trenetics.io
today at 21:27:24  Attempting to renew cert (npm-4) from /etc/letsencrypt/renewal/npm-4.conf produced an unexpected error: Some challenges have failed.. Skipping.
today at 21:27:24  All renewal attempts failed. The following certs could not be renewed:
today at 21:27:24    /etc/letsencrypt/live/npm-20/fullchain.pem (failure)
today at 21:27:24    /etc/letsencrypt/live/npm-21/fullchain.pem (failure)
today at 21:27:24    /etc/letsencrypt/live/npm-22/fullchain.pem (failure)
today at 21:27:24    /etc/letsencrypt/live/npm-30/fullchain.pem (failure)
today at 21:27:24    /etc/letsencrypt/live/npm-34/fullchain.pem (failure)
today at 21:27:24    /etc/letsencrypt/live/npm-35/fullchain.pem (failure)
today at 21:27:24    /etc/letsencrypt/live/npm-36/fullchain.pem (failure)
today at 21:27:24    /etc/letsencrypt/live/npm-4/fullchain.pem (failure)
today at 21:27:24  8 renew failure(s), 0 parse failure(s)
today at 21:27:24  
today at 21:27:24      at ChildProcess.exithandler (child_process.js:308:12)
today at 21:27:24      at ChildProcess.emit (events.js:314:20)
today at 21:27:24      at maybeClose (internal/child_process.js:1051:16)
today at 21:27:24      at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)`
```

If i try to renew one of the above certs manually: (it works, but extremely slow)

```
today at 21:29:26  [4/14/2021] [7:29:26 PM] [SSL      ] › ℹ  info      Renewing Let'sEncrypt certificates via Cloudflare for Cert #35: xxx.xxx.xx
today at 21:34:26  [4/14/2021] [7:34:26 PM] [SSL      ] › ℹ  info      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
today at 21:34:26  Processing /etc/letsencrypt/renewal/npm-35.conf
today at 21:34:26  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
today at 21:34:26  
today at 21:34:26  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
today at 21:34:26  new certificate deployed without reload, fullchain is
today at 21:34:26  /etc/letsencrypt/live/npm-35/fullchain.pem
today at 21:34:26  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
today at 21:34:26  
today at 21:34:26  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
today at 21:34:26  
today at 21:34:26  Congratulations, all renewals succeeded. The following certs have been renewed:
today at 21:34:26    /etc/letsencrypt/live/npm-35/fullchain.pem (success)
today at 21:34:26  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

I get a time out in UI: (but the cert, renews in background)

![image](https://user-images.githubusercontent.com/56591389/114769663-c90b7e80-9d6a-11eb-8437-eb948e09547f.png)

**Operating System**
Ubuntu Docker - Latest image of NPM pulled

Any ideas?

**Comment by jonasled** [comment]
I had the same problem, it looks like certbot shippped with alpine is a older version, which isn't anymore supported. I've switched in my custom container to a install via pip and then everything works again. (https://gitlab.jonasled.de/jonasled/nginx-proxy-manager-dark/-/blob/master/docker/Dockerfile)

**Comment by jonasled** [comment]
Interesting news. I had the problem again on the new debian based container and after executing `certbot renew` by hand and restarting the container it worked
