### ISSUE TITLE
Netcup DNS Challenge doesn´t work

### ISSUE THREAD

**Issue by Twilek-de** [jc21/nginx-proxy-manager#1166]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When I try to use the DNS challenge I get an internal ereor:

```
Error: Command failed: /opt/certbot/bin/certbot certonly --non-interactive --cert-name "npm-6" --agree-tos --email "xxx@gmx.de" --domains "test.xxx.de" --authenticator certbot-dns-netcup:dns-netcup --certbot-dns-netcup:dns-netcup-credentials "/etc/letsencrypt/credentials/credentials-6"
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugin legacy name certbot-dns-netcup:dns-netcup may be removed in a future version. Please use dns-netcup instead.
Plugins selected: Authenticator certbot-dns-netcup:dns-netcup, Installer None
Performing the following challenges:
dns-01 challenge for test.xxx.de
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Domain Names *
```

The Letsencrypt log shows:

```
2021-06-09 20:45:10,870:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-06-09 20:45:10,870:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-06-09 20:45:10,871:DEBUG:lexicon.providers.netcup:login({})
2021-06-09 20:45:10,872:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ccp.netcup.net:443
2021-06-09 20:45:10,915:DEBUG:urllib3.connectionpool:https://ccp.netcup.net:443 "POST /run/webservice/servers/endpoint.php?JSON HTTP/1.1" 200 228
2021-06-09 20:45:10,918:DEBUG:lexicon.providers.netcup:infoDnsZone({'domainname': 'test.xxx.de'})
2021-06-09 20:45:10,920:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ccp.netcup.net:443
2021-06-09 20:45:10,960:DEBUG:urllib3.connectionpool:https://ccp.netcup.net:443 "POST /run/webservice/servers/endpoint.php?JSON HTTP/1.1" 200 189
2021-06-09 20:45:10,962:DEBUG:lexicon.providers.netcup:login({})
2021-06-09 20:45:10,964:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ccp.netcup.net:443
2021-06-09 20:45:11,000:DEBUG:urllib3.connectionpool:https://ccp.netcup.net:443 "POST /run/webservice/servers/endpoint.php?JSON HTTP/1.1" 200 228
2021-06-09 20:45:11,003:DEBUG:lexicon.providers.netcup:infoDnsZone({'domainname': 'xxx.de'})
2021-06-09 20:45:11,005:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ccp.netcup.net:443
2021-06-09 20:45:11,070:DEBUG:urllib3.connectionpool:https://ccp.netcup.net:443 "POST /run/webservice/servers/endpoint.php?JSON HTTP/1.1" 200 239
2021-06-09 20:45:11,073:ERROR:certbot._internal.error_handler:Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
2021-06-09 20:45:11,073:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1435, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1304, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 444, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 424, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/plugins/dns_common.py", line 60, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/opt/certbot/lib/python3.7/site-packages/certbot_dns_netcup.py", line 59, in _perform
    domain, validation_name, validation)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/plugins/dns_common_lexicon.py", line 48, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'
2021-06-09 20:45:11,075:ERROR:certbot._internal.log:An unexpected error occurred:
2021-06-09 20:45:11,075:ERROR:certbot._internal.log:TypeError: create_record() got an unexpected keyword argument 'type'
```

**Nginx Proxy Manager Version**
v2.9.3

**To Reproduce**
1. Go to 'Add SSL Certificate'
2. Click on 'DNS Challenge -> Netcup'
3. Scroll down to 'error'

**Comment by chaptergy** [comment]
See https://github.com/jc21/nginx-proxy-manager/issues/1119#issuecomment-846843724
