### ISSUE TITLE
DNS challenge DYNU configuration

### ISSUE THREAD

**Issue by suhrke** [jc21/nginx-proxy-manager#1189]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes
  - 
**Describe the bug**

Hello, 
I wanted to use the DNS challenge plugin Dynu, and this wants to get
certbot_dns_dynu:dns_dynu_auth_token = YOUR_DYNU_AUTH_TOKEN

I replaced YOUR_DYNU_AUTH_TOKEN with my own api token at dynu.com

and got only 

"Internal error" 
and
 "This section requires some knowledge about Certbot and its DNS plugins. Please consult the respective plugins documentation." 

In the corresponding python script inside the container /opt/certbot/lib/python3.7/site-packages/certbot_dns_dynu/dns_dynu.py I found also only the reference to the dynu auth token. 
I use this DNS challenge on another platform (proxmox-ve) which uses auth-token and oauth2 Client-ID/secret what works properly. So I look for a way to configure this in nginx proxy manager properly, but found not any hint.

**Nginx Proxy Manager Version**

**To Reproduce**
1. Go to '...' dynu.com, create the subdomain/address record for the affected certificate
2. create a new proxy with this dns name
3. go to SSL
4. request a new SSL certificate with LE
5. take "Use a DNS challenge"
6. choose "dynu"
7. put yout authentication token into the configuration field like
    certbot_dns_dynu:dns_dynu_auth_token = MY_OWN_DYNU_AUTH_TOKEN
8. put in yout LE account email
9. choose "I agree to .."
10. optional choose "Force SSL" and "HTTP/2 support"
11. choose "Save"

**Expected behavior**

correct pull a certificate from letsencrypt with dns challenge provided by dynu.com

**Screenshots**

<img width="370" alt="Screenshot 2021-06-19 001030" src="https://user-images.githubusercontent.com/16483530/122620359-0ce47200-d093-11eb-9710-1e2910119a5d.png">

![image](https://user-images.githubusercontent.com/16483530/122620865-53869c00-d094-11eb-836c-7ecb25e5f30e.png)

**Operating System**

ubuntu 20.04 LTS / Docker version 20.10.7, build f0df350

**Additional context**

**Comment by chaptergy** [comment]
Could you take a look into the logs of the npm container to see what the actual error is?

**Comment by sillydanny** [comment]
I have the same issue about the DNS challenge, 
> npm  | [7/3/2023] [9:06:16 AM] [Nginx    ] › ℹ  info      Reloading Nginx
> npm  | [7/3/2023] [9:06:16 AM] [Express  ] › ⚠  warning   Command failed: . > > /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-godaddy~=0.2.0  && deactivate
> npm  | ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /opt/certbot/lib/python3.7/site-packages

**Comment by randomDrops** [comment]
Found a solution. Guess there might be a better solution.
Replace the text with "API-Key:<api-key>". Please omit the quotes.

**Comment by randomDrops** [comment]
Update: I made a certificate with another Dynu subdomain name. It might prompt you an error prompt, but you will succeed if you keep on trying. There'll be another weird outcome - there'll be 2 certificates generated. I was in the same situation earlier today. Back then, I thought I clicked the button twice.

**Comment by DairyWeb3638077** [comment]
I get this error

```md
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-29" --agree-tos --email "MY EMAIL" --domains "MY DOMAIN" --authenticator dns-dynu --dns-dynu-credentials "/etc/letsencrypt/credentials/credentials-29" --dns-dynu-propagation-seconds 120
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in 
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in 
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 21, in 
    import josepy as jose
  File "/opt/certbot/lib/python3.7/site-packages/josepy/__init__.py", line 40, in 
    from josepy.json_util import (
  File "/opt/certbot/lib/python3.7/site-packages/josepy/json_util.py", line 24, in 
    from OpenSSL import crypto
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in 
    from OpenSSL import crypto, SSL
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1517, in 
    class X509StoreFlags(object):
  File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket. (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe. (node:net:301:12)
```

**Comment by yuriw** [comment]
I see this too in 2024
Was there any solutions found for this issue?

**Comment by yurii-karadzhov** [comment]
```pip install certbot-dns-dynu``` solves the issue
