### ISSUE TITLE
"Connection refused" Status: 400

### ISSUE THREAD

**Issue by Hukuma1** [jc21/nginx-proxy-manager#1275]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - (Yes) / No
- Are you sure you're not using someone else's docker image?
  - (Yes) / No
- Have you searched for similar issues (both open and closed)?
  - (Yes) / No

**Describe the bug**
Unable to issue SSL certificates.

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log,
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.,
Some challenges have failed.,
[7/30/2021] [12:50:35 AM] [Express  ] › ⚠  warning   Command failed: certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-8" --agree-tos --email "MYEMAIL@gmail.com" --preferred-challenges "dns,http" --domains "SUBDOMAIN.DOMAIN.com" 
```

letsencrypt.log
```
[root@docker-7f2ec9245aec:/var/log/letsencrypt]# cat letsencrypt.log
2021-07-30 00:39:55,821:DEBUG:certbot._internal.main:certbot version: 1.17.0
2021-07-30 00:39:55,821:DEBUG:certbot._internal.main:Location of certbot entry point: /opt/certbot/bin/certbot
2021-07-30 00:39:55,821:DEBUG:certbot._internal.main:Arguments: ['--non-interactive', '--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-7', '--agree-tos', '--email', 'MYEMAIL', '--preferred-challenges', 'dns,http', '--domains', 'SUBDOMAIN.MYDOMAIN.com']
2021-07-30 00:39:55,821:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-07-30 00:39:55,829:DEBUG:certbot._internal.log:Root logging level set at 30
2021-07-30 00:39:55,829:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-07-30 00:39:55,831:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f9465c63550>
Prep: True
2021-07-30 00:39:55,831:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f9465c63550> and installer None
2021-07-30 00:39:55,831:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-07-30 00:39:55,836:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/141170680', new_authzr_uri=None, terms_of_service=None), 936dfcbdf1c671e9f13a5ed9610442f2, Meta(creation_dt=datetime.datetime(2021, 7, 29, 19, 18, 21, tzinfo=<UTC>), creation_host='b54dc00fe2b9', register_to_eff=None))>
2021-07-30 00:39:55,836:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-07-30 00:39:55,838:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-07-30 00:39:56,046:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-07-30 00:39:56,047:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 30 Jul 2021 00:40:16 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "P-7kGfo1fVY": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-07-30 00:39:56,048:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for SUBDOMAIN.MYDOMAIN.com
2021-07-30 00:39:56,268:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0006_key-certbot.pem
2021-07-30 00:39:56,269:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0006_csr-certbot.pem
2021-07-30 00:39:56,270:DEBUG:acme.client:Requesting fresh nonce
2021-07-30 00:39:56,270:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-07-30 00:39:56,322:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-07-30 00:39:56,322:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 30 Jul 2021 00:40:17 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102cJIXI75uP3Ms8kVr3UOJkm2RNbVF2VxTYfIAIPWYRlU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-07-30 00:39:56,323:DEBUG:acme.client:Storing nonce: 0102cJIXI75uP3Ms8kVr3UOJkm2RNbVF2VxTYfIAIPWYRlU
2021-07-30 00:39:56,323:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "SUBDOMAIN.MYDOMAIN.com"\n    }\n  ]\n}'
2021-07-30 00:39:56,324:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTQxMTcwNjgwIiwgIm5vbmNlIjogIjAxMDJjSklYSTc1dVAzTXM4a1ZyM1VPSmttMlJOYlZGMlZ4VFlmSUFJUFdZUmxVIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "ZUvzsS7T1fDmV4zjcd70xBMIo91rHkBaySnU4yY4RFy9dsfqYl4y9bSR3L0CiM3tHZ6t5JnExAp5ETOMe6wAntc_bLPyvTgNUKB0kRwt_aXFwAkR8dcIPeQuchHqv2hQAvaRSMCU3jn8k_O-_h4yDd0C1qQTGzgnp68NWqOsGNWqPjq_vVfKv0jbdAM1Ufy57M6fOUtipXW_BxCWhK8_bAiXLCz1PeqBg8xM-BL9zmUHGDzs7VSqP0lAtBFXfz7HG1TYDIT52oQFYMjfa7V5kJzPTVgdVme1wYDOq-eY4Oez0Q97BSV1VrtUa8t0VgYMfRbxN8Z4rhAU954e5clqBw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInByb3h5LmltbmlraXRhLmNvbSIKICAgIH0KICBdCn0"
}
2021-07-30 00:39:56,628:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 341
2021-07-30 00:39:56,629:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 30 Jul 2021 00:40:17 GMT
Content-Type: application/json
Content-Length: 341
Connection: keep-alive
Boulder-Requester: 141170680
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/141170680/13172796450
Replay-Nonce: 0101c0guGvEAnMYm3y3NsytiQUBVLjntGIyGGemOZ8iWI18
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-08-06T00:40:17Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "SUBDOMAIN.MYDOMAIN.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/17334397170"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/141170680/13172796450"
}
2021-07-30 00:39:56,630:DEBUG:acme.client:Storing nonce: 0101c0guGvEAnMYm3y3NsytiQUBVLjntGIyGGemOZ8iWI18
2021-07-30 00:39:56,630:DEBUG:acme.client:JWS payload:
b''
2021-07-30 00:39:56,633:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/17334397170:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTQxMTcwNjgwIiwgIm5vbmNlIjogIjAxMDFjMGd1R3ZFQW5NWW0zeTNOc3l0aVFVQlZMam50R0l5R0dlbU9aOGlXSTE4IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xNzMzNDM5NzE3MCJ9",
  "signature": "CC7vwKvCY5z0tUApBJO8KHCf0_lsUJokJm60dGzYkb8vMsJ8yYxE5lEchG1L_4pJAKTyuaEan4W_TaoXUEyeIw8i-VrmgHZRn_P3vn1zav7SqFNv6ecp7ciu6DowQ6eh2bSI4Gs-JKS-Za6eDS8vfz30fSEQwo5GfTzsh04w719yU7XFkFEsbExQMgMT0xDE3NDBtSGyN3ZSFtMjxOVdQpQthrggU3xrQp78i5Rx1rHWVEhFiFiXpy7E9CShYmE6NWBf87APka7vA0-nO2mzKi2wwBKQo_gtb0KmL_aUTvbGnf2GiRs9AfBijYXvLTQnBEgiY5v-I-PxkRUd9EMefg",
  "payload": ""
}
2021-07-30 00:39:56,733:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/17334397170 HTTP/1.1" 200 799
2021-07-30 00:39:56,734:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 30 Jul 2021 00:40:17 GMT
Content-Type: application/json
Content-Length: 799
Connection: keep-alive
Boulder-Requester: 141170680
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102FN-9pbXFk3tbVqOUZ70anFTnKtGwSyrCkbGp3QZQcmc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "SUBDOMAIN.MYDOMAIN.com"
  },
  "status": "pending",
  "expires": "2021-08-06T00:40:17Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/17334397170/3AgRbw",
      "token": "soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/17334397170/4OZIYQ",
      "token": "soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/17334397170/-gj_yg",
      "token": "soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ"
    }
  ]
}
2021-07-30 00:39:56,734:DEBUG:acme.client:Storing nonce: 0102FN-9pbXFk3tbVqOUZ70anFTnKtGwSyrCkbGp3QZQcmc
2021-07-30 00:39:56,735:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-07-30 00:39:56,735:INFO:certbot._internal.auth_handler:http-01 challenge for SUBDOMAIN.MYDOMAIN.com
2021-07-30 00:39:56,735:INFO:certbot._internal.plugins.webroot:Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
2021-07-30 00:39:56,736:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /data/letsencrypt-acme-challenge/.well-known/acme-challenge
2021-07-30 00:39:56,738:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /data/letsencrypt-acme-challenge/.well-known/acme-challenge/soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ
2021-07-30 00:39:56,738:DEBUG:acme.client:JWS payload:
b'{}'
2021-07-30 00:39:56,741:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/17334397170/3AgRbw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTQxMTcwNjgwIiwgIm5vbmNlIjogIjAxMDJGTi05cGJYRmszdGJWcU9VWjcwYW5GVG5LdEd3U3lyQ2tiR3AzUVpRY21jIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My8xNzMzNDM5NzE3MC8zQWdSYncifQ",
  "signature": "Tt-iQmIes_8khjfLLg9wqBfLCy239qC7YNC-AwdrYf6hUUg-w_zts8qIagClRUUn01ivOhgr-gCmQICm0Stwclx6lrbS6lDfeRWwkzkfdGLj4b4bdhx18fc-6yKAdlfzlD01yeifksWHNCVIDmgT-BUNOwMqpxrlYmIS-xe782X5hJmRhOVCoPlFlFZoTD4qJ161dj-T2ndlaML_nrJVUz6b-ux_ZlZ0v7N4eSRhd5EDbt6F7d959_FoTHp8Kgg3Kmb-4QJjQ8fhhmB5JbzBnBceO35t1GfPUIqwwSUJPFFrmq-nsy1oN3eecUQptnoEZLMdJveTGZyUraYZaleeBA",
  "payload": "e30"
}
2021-07-30 00:39:56,850:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/17334397170/3AgRbw HTTP/1.1" 200 186
2021-07-30 00:39:56,852:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 30 Jul 2021 00:40:17 GMT
Content-Type: application/json
Content-Length: 186
Connection: keep-alive
Boulder-Requester: 141170680
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/17334397170>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/17334397170/3AgRbw
Replay-Nonce: 0101WwvwFzO1SawySv4oPeG3IlDJwN_9UCvfGo5hjc_0XU8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/17334397170/3AgRbw",
  "token": "soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ"
}
2021-07-30 00:39:56,852:DEBUG:acme.client:Storing nonce: 0101WwvwFzO1SawySv4oPeG3IlDJwN_9UCvfGo5hjc_0XU8
2021-07-30 00:39:56,853:INFO:certbot._internal.auth_handler:Waiting for verification...
2021-07-30 00:39:57,854:DEBUG:acme.client:JWS payload:
b''
2021-07-30 00:39:57,858:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/17334397170:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTQxMTcwNjgwIiwgIm5vbmNlIjogIjAxMDFXd3Z3RnpPMVNhd3lTdjRvUGVHM0lsREp3Tl85VUN2ZkdvNWhqY18wWFU4IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xNzMzNDM5NzE3MCJ9",
  "signature": "i-XUTiKoUo0sOthpLwEpY5W6ZPbAGF7569a_4U_-WvOEvRMpC9DlWJfvIF-ze7GnbZiQIcqzIVvC2Ejm6IeAbcwFcmYOtiaDdeGQA1e8nC9eAL9zOIUIRkN-eBDPOqrCKhErATajAHlUQAkKYxdeh8cpBxJZC5PeVK0D6X_E8NdqpFUJ4Rnahsd8tWA2Ag2HLRHGi_o0HVcg8-5JL-TaHbK4TpnhXIc7Fgtgpe5wK0Xz1SxhZvK7EAx8mQHD7JdjYM7eiXosQJAcPIBsrp6Eob0DrXI4O8k1ke8hj1n3sxPloqezE0ZA24ySKVmDw4TsMhodDcevGTS7bnR8XAT97w",
  "payload": ""
}
2021-07-30 00:39:57,945:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/17334397170 HTTP/1.1" 200 1024
2021-07-30 00:39:57,945:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 30 Jul 2021 00:40:18 GMT
Content-Type: application/json
Content-Length: 1024
Connection: keep-alive
Boulder-Requester: 141170680
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0101UsoaOogUJ8by5JRXN58gbtFBZMR8lCTCs6sUxC6JfCU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "SUBDOMAIN.MYDOMAIN.com"
  },
  "status": "invalid",
  "expires": "2021-08-06T00:40:17Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://SUBDOMAIN.MYDOMAIN.com/.well-known/acme-challenge/soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ: Connection refused",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/17334397170/3AgRbw",
      "token": "soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ",
      "validationRecord": [
        {
          "url": "http://SUBDOMAIN.MYDOMAIN.com/.well-known/acme-challenge/soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ",
          "hostname": "SUBDOMAIN.MYDOMAIN.com",
          "port": "80",
          "addressesResolved": [
            "MYIP"
          ],
          "addressUsed": "MYIP"
        }
      ],
      "validated": "2021-07-30T00:40:17Z"
    }
  ]
}
2021-07-30 00:39:57,945:DEBUG:acme.client:Storing nonce: 0101UsoaOogUJ8by5JRXN58gbtFBZMR8lCTCs6sUxC6JfCU
2021-07-30 00:39:57,946:INFO:certbot._internal.auth_handler:Challenge failed for domain SUBDOMAIN.MYDOMAIN.com
2021-07-30 00:39:57,946:INFO:certbot._internal.auth_handler:http-01 challenge for SUBDOMAIN.MYDOMAIN.com
2021-07-30 00:39:57,946:DEBUG:certbot.display.util:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: SUBDOMAIN.MYDOMAIN.com
  Type:   connection
  Detail: Fetching http://SUBDOMAIN.MYDOMAIN.com/.well-known/acme-challenge/soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2021-07-30 00:39:57,946:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 93, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 181, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-07-30 00:39:57,946:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-07-30 00:39:57,946:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-07-30 00:39:57,946:DEBUG:certbot._internal.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/soLaQsrz5ftguPfc-j0Jdkwg-5m22JUlzg1TcctyBSQ
2021-07-30 00:39:57,947:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2021-07-30 00:39:57,947:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1574, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1435, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 128, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 445, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 375, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 425, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 93, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 181, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2021-07-30 00:39:57,948:ERROR:certbot._internal.log:Some challenges have failed.
```

**Nginx Proxy Manager Version**
v2.9.6

**Expected behavior**
SSL certificate should issue? Used to work just fine, not sure what has changed...

**Screenshots**

**Operating System**
Docker in OpenMediaVault

**Additional context**
Was working fine, and now seems to not be. Only major changes I've made were making a Docker Stack vs individual containers. So I now start all my containers from a docker-compose syntax. No other errors pop up though?

**Comment by Hukuma1** [comment]
Not sure why, but apparently changing the ports caused my errors. Leaving everything at default makes it work again. Have to check up on this later on if there is a way to switch out some ports, but right now please disregard. Sorry!

**Comment by Hukuma1** [comment]
If anyone finds this issue via Google, make sure your port 80 (and 443) are open on your router. My port 80 port forward got disabled for some reason.
