### ISSUE TITLE
Error creating certificate

### ISSUE THREAD

**Issue by talesam** [jc21/nginx-proxy-manager#1492]
Version NPM: 2.9.1

```
[root@docker-2975096e2791:/app]# cat /var/log/letsencrypt/letsencrypt.log
2021-10-17 03:29:56,217:DEBUG:certbot._internal.main:certbot version: 1.19.0
2021-10-17 03:29:56,217:DEBUG:certbot._internal.main:Location of certbot entry point: /opt/certbot/bin/certbot
2021-10-17 03:29:56,217:DEBUG:certbot._internal.main:Arguments: ['--non-interactive', '--config', '/etc/letsencrypt.ini', '--cert-name', 'npm-12', '--agree-tos', '--authenticator', 'webroot', '--email', 'talesam@gmail.com', '--preferred-challenges', 'dns,http', '--domains', 'd1.t4l35.host']
2021-10-17 03:29:56,217:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-10-17 03:29:56,233:DEBUG:certbot._internal.log:Root logging level set at 30
2021-10-17 03:29:56,234:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-10-17 03:29:56,236:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0xffffa1d0c400>
Prep: True
2021-10-17 03:29:56,236:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0xffffa1d0c400> and installer None
2021-10-17 03:29:56,236:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-10-17 03:29:56,253:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/236307560', new_authzr_uri=None, terms_of_service=None), 9c551d352acbefa090bc2138f79d75f1, Meta(creation_dt=datetime.datetime(2021, 10, 12, 15, 49, 35, tzinfo=<UTC>), creation_host='2975096e2791', register_to_eff=None))>
2021-10-17 03:29:56,254:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-10-17 03:29:56,256:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-10-17 03:29:56,839:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-10-17 03:29:56,840:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 17 Oct 2021 03:29:56 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "XowMEoSXdt0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-10-17 03:29:56,840:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for d1.t4l35.host
2021-10-17 03:29:56,843:DEBUG:certbot.crypto_util:Generating ECDSA key (2048 bits): /etc/letsencrypt/keys/0007_key-certbot.pem
2021-10-17 03:29:56,846:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0007_csr-certbot.pem
2021-10-17 03:29:56,847:DEBUG:acme.client:Requesting fresh nonce
2021-10-17 03:29:56,847:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-10-17 03:29:57,041:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-10-17 03:29:57,042:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 17 Oct 2021 03:29:56 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001YjEkmW33_JAFpiw7_E2924dl2Xnygs3KpdWqoHZgUi0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-10-17 03:29:57,042:DEBUG:acme.client:Storing nonce: 0001YjEkmW33_JAFpiw7_E2924dl2Xnygs3KpdWqoHZgUi0
2021-10-17 03:29:57,042:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "d1.t4l35.host"\n    }\n  ]\n}'
2021-10-17 03:29:57,046:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjM2MzA3NTYwIiwgIm5vbmNlIjogIjAwMDFZakVrbVczM19KQUZwaXc3X0UyOTI0ZGwyWG55Z3MzS3BkV3FvSFpnVWkwIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "e2sjQWgARbvVcF0Dag1v4_R85lWFv4Aandjt4S96a8le2Y_eY8uVdkP2Mcvef6q_rwqyuvjgOrxjUK6Mwd769hcoC_fkPFVeFbTh4qMCQPvf_AjM-X8WaJOGtp1y1C-nRqunwfSMLsE5GlJ6ffyJPaOa4j_3_tglPcxYC35XsiLmZ0HmXEmVvLTfhgXcHSEV8yXmFtGhxztmh5EdD6Vl6UIn5sNAIkgQUHk6hRFSQzaliuUZWzdj1j6LuhZSNghMIwOwm0BDJG8QRX5Pi9gufZh6fYLcg1vheWmuDK7ewz86oc6moGhXWgAL0FgH7nRSZ6JtaD1oHW_09jqkR3k43A",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImQxLnQ0bDM1Lmhvc3QiCiAgICB9CiAgXQp9"
}
2021-10-17 03:29:57,251:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 336
2021-10-17 03:29:57,252:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 17 Oct 2021 03:29:57 GMT
Content-Type: application/json
Content-Length: 336
Connection: keep-alive
Boulder-Requester: 236307560
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/236307560/32472877190
Replay-Nonce: 0001wykEFI-vPbe5nActELm5qtDnuOuCywoTboyLd9_SqvU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-10-24T03:28:42Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "d1.t4l35.host"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/40640332880"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/236307560/32472877190"
}
2021-10-17 03:29:57,252:DEBUG:acme.client:Storing nonce: 0001wykEFI-vPbe5nActELm5qtDnuOuCywoTboyLd9_SqvU
2021-10-17 03:29:57,252:DEBUG:acme.client:JWS payload:
b''
2021-10-17 03:29:57,255:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/40640332880:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjM2MzA3NTYwIiwgIm5vbmNlIjogIjAwMDF3eWtFRkktdlBiZTVuQWN0RUxtNXF0RG51T3VDeXdvVGJveUxkOV9TcXZVIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My80MDY0MDMzMjg4MCJ9",
  "signature": "gDPVrprFjNBB4eAaAIXRexlT0Di3femNgaJMff_h7J7u2wfPNt7uRfxGf6yAg7dh9HtxdwUoLGr-TpKL9dm9MnXEsC9EJ0dMEATd3rFVg-I1kOQq90aIcUTl4LNJAhYtX_de-LZDHvxyUimswHQhFUQTywWKKF59UD67guBP0Conc7gmNQaLTEJcRU95i2AL0EQ1GAiSSmTjbWeCvqjGU6n_TX1YFx2nbHIKDDrHTGgnNxtSpXXhzUPVnObyoFvMrIL3fJSd751XEGD6OkYnjlPGKzFqGSR0V69SW0QkHmZxsZdjw09Q-pYxk-K4NNa6Jqs6eOrGM0710ADrGWzGWw",
  "payload": ""
}
2021-10-17 03:29:57,454:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/40640332880 HTTP/1.1" 200 794
2021-10-17 03:29:57,455:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 17 Oct 2021 03:29:57 GMT
Content-Type: application/json
Content-Length: 794
Connection: keep-alive
Boulder-Requester: 236307560
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001ulNgzIonzI_Xjud5zIwl2DcJWtBv-sMnxmIJ7kQ0hsw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "d1.t4l35.host"
  },
  "status": "pending",
  "expires": "2021-10-24T03:28:42Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/40640332880/GUztXQ",
      "token": "WDl7DflkWU6GjJ4fP7u6ZBFM6Ir5QbC9fP6rQ6zjs-Q"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/40640332880/m6ZE5g",
      "token": "WDl7DflkWU6GjJ4fP7u6ZBFM6Ir5QbC9fP6rQ6zjs-Q"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/40640332880/8PdzqQ",
      "token": "WDl7DflkWU6GjJ4fP7u6ZBFM6Ir5QbC9fP6rQ6zjs-Q"
    }
  ]
}
2021-10-17 03:29:57,455:DEBUG:acme.client:Storing nonce: 0001ulNgzIonzI_Xjud5zIwl2DcJWtBv-sMnxmIJ7kQ0hsw
2021-10-17 03:29:57,455:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-10-17 03:29:57,456:INFO:certbot._internal.auth_handler:http-01 challenge for d1.t4l35.host
2021-10-17 03:29:57,456:INFO:certbot._internal.plugins.webroot:Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
2021-10-17 03:29:57,456:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /data/letsencrypt-acme-challenge/.well-known/acme-challenge
2021-10-17 03:29:57,458:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /data/letsencrypt-acme-challenge/.well-known/acme-challenge/WDl7DflkWU6GjJ4fP7u6ZBFM6Ir5QbC9fP6rQ6zjs-Q
2021-10-17 03:29:57,458:DEBUG:acme.client:JWS payload:
b'{}'
2021-10-17 03:29:57,461:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/40640332880/GUztXQ:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjM2MzA3NTYwIiwgIm5vbmNlIjogIjAwMDF1bE5neklvbnpJX1hqdWQ1ekl3bDJEY0pXdEJ2LXNNbnhtSUo3a1EwaHN3IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbC12My80MDY0MDMzMjg4MC9HVXp0WFEifQ",
  "signature": "PKUIcjiDHMZ0JIkGKtb78Ds_xIbL7ahfohTJgUWn9gQ_0IwQb_6ecOsS0u1hxYrExK6QO84dJzPpAruDkpv16w8VBC2ZlnMFGy4J9tDJnuv7hKfb42AsQON_cxs-n1VelWoL6HEAM4h7sczsAQacGN-PrFGuhpoUD2chfC1BEm2_uYak2WWpXwW4UgYO0dDlFc_JbgjxWN6xX9qgUDvGLRRN4R94JYkg7GHMEgyetStfzjn6r-t_U0BNKIjW-7HIBUWRwNfGXAgjvfozKUl0H9tHpa1n5oHQxkAnKKxhhe_mRVPouNX-p2Yr2KFYWudetU9d0vdKA1WppJkUel0ILg",
  "payload": "e30"
}
2021-10-17 03:30:02,663:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/40640332880/GUztXQ HTTP/1.1" 500 116
2021-10-17 03:30:02,664:DEBUG:acme.client:Received response:
HTTP 500
Server: nginx
Date: Sun, 17 Oct 2021 03:30:02 GMT
Content-Type: application/problem+json
Content-Length: 116
Connection: keep-alive
Boulder-Requester: 236307560
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001vt83m1y7AG3kg64E8-epcogpMvrutofEfmOlcqnRg2Y

{
  "type": "urn:ietf:params:acme:error:serverInternal",
  "detail": "Unable to update challenge",
  "status": 500
}
2021-10-17 03:30:02,665:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
    self.acme.answer_challenge(achall.challb, resp)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 163, in answer_challenge
    response = self._post(challb.uri, response)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 92, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 1227, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 1240, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 1087, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:serverInternal :: The server experienced an internal error :: Unable to update challenge

2021-10-17 03:30:02,665:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-10-17 03:30:02,665:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-10-17 03:30:02,665:DEBUG:certbot._internal.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/WDl7DflkWU6GjJ4fP7u6ZBFM6Ir5QbC9fP6rQ6zjs-Q
2021-10-17 03:30:02,665:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2021-10-17 03:30:02,666:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1572, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1432, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 133, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 454, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 384, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/client.py", line 434, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
    self.acme.answer_challenge(achall.challb, resp)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 163, in answer_challenge
    response = self._post(challb.uri, response)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 92, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 1227, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 1240, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/lib/python3.7/site-packages/acme/client.py", line 1087, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:serverInternal :: The server experienced an internal error :: Unable to update challenge
2021-10-17 03:30:02,666:ERROR:certbot._internal.log:An unexpected error occurred:
2021-10-17 03:30:02,667:ERROR:certbot._internal.log:The server experienced an internal error :: Unable to update challenge
```

**Comment by marieldejesus12** [comment]
my log...


[10/17/2021] [3:40:00 PM] [Nginx    ] › ℹ  info      Reloading Nginx

[10/17/2021] [3:40:00 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #71: testedotales2.marielejesus12.tech

[10/17/2021] [3:40:00 PM] [SSL      ] › ℹ  info      Command: certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-71" --agree-tos --authenticator webroot --email "marieldejesus12@gmail.com" --preferred-challenges "dns,http" --domains "testedotales2.marielejesus12.tech" 

[10/17/2021] [3:40:04 PM] [Nginx    ] › ℹ  info      Reloading Nginx

[10/17/2021] [3:40:04 PM] [Express  ] › ⚠  warning   Command failed: certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-71" --agree-tos --authenticator webroot --email "marieldejesus12@gmail.com" --preferred-challenges "dns,http" --domains "testedotales2.marielejesus12.tech" 

Saving debug log to /var/log/letsencrypt/letsencrypt.log

Some challenges have failed.

Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by chaptergy** [comment]
The ACME server returns a 500 error, which means there was an error on their side, so there isn't anything we could do about it. Maybe asking over in letsencrypt forums might yield more information. It could also have something to do with their [rate limit](https://letsencrypt.org/docs/rate-limits/).

**Comment by talesam** [comment]
> O servidor ACME retorna um erro 500, o que significa que houve um erro do lado deles, então não há nada que possamos fazer a respeito. Talvez perguntar nos fóruns letsencrypt possa render mais informações. Também pode ter algo a ver com seu [limite de taxa](https://letsencrypt.org/docs/rate-limits/) .

This rate limit is related to email, correct? Do you know where I see the limit? I didn't create many certificates, I don't think that's it, but I'll see it on their forum.

I wanted to put the cloudflare certificate to work, but whenever I tried it gave an error, is there somewhere explaining how to do it correctly?
