### ISSUE TITLE
MariaDB not working

### ISSUE THREAD

**Issue by zhuoyang** [jc21/nginx-proxy-manager#19]
I am trying to run this on my raspberry pi but this error keeps looping when I attach to the docker container, it doesn't shows up when I set my engine to mysql

`[9/19/2018] [6:05:56 PM] [Global  ] › ✖  error                        Cannot find module './dialects/mariadb/index.js' { Error: Cannot find module './dialects/mariadb/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Knex (/app/node_modules/knex/lib/index.js:49:15)
    at Object.<anonymous> (/app/src/backend/db.js:27:33)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/app/src/backend/migrate.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10) code: 'MODULE_NOT_FOUND' }
nginx: [emerg] mkdir() "/var/cache/nginx/proxy_temp" failed (2: No such file or directory)
nginx: [emerg] mkdir() "/var/cache/nginx/proxy_temp" failed (2: No such file or directory)
nginx: [emerg] mkdir() "/var/cache/nginx/proxy_temp" failed (2: No such file or directory)
`

**Comment by jc21** [comment]
It looks like you've set your config file to be `mariadb` instead of `mysql` for the `engine` field. The mysql engine works for maria db as well.

I'm very interested to see how you go with the rpi builds, since I haven't tested it :)

**Comment by zhuoyang** [comment]
another error shows up when using mysql engine

> [9/20/2018] [8:01:27 AM] [Migrate ] › ℹ  info                         Current database version: none
[9/20/2018] [8:01:27 AM] [Migrate ] › ℹ  info                         [initial-schema] Migrating Up...
migration file "20180618015850_initial.js" failed
migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1
[9/20/2018] [8:01:27 AM] [Global  ] › ✖  error                        create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1

**Comment by jc21** [comment]
What version of Mariadb do you have installed? You might be better off with a newer version running in another docker container

**Comment by jc21** [comment]
How did you go with this?

**Comment by zhuoyang** [comment]
I am sorry for late reply, finally got it working after my long vacation
There is only a few mariadb docker container for arm and this [one](https://hub.docker.com/r/yobasystems/alpine-mariadb/) is working for me.

I keep seeing this log spam from the container, is there something wrong?
```
nginx: [emerg] mkdir() "/var/cache/nginx/proxy_temp" failed (2: No such file or directory)
nginx: [emerg] mkdir() "/var/cache/nginx/proxy_temp" failed (2: No such file or directory)
```

**Comment by zhuoyang** [comment]
never mind, manually creating /var/cache/nginx directory solved it 👍

**Comment by daniel-jirca** [comment]
Looks like I get a similar SQL related error when first starting the server.
Using images `jc21/nginx-proxy-manager:latest-armv7l` and `linuxserver/mariadb:latest`.

```apps_nginx-proxy-manager.1.t3v2dwe4msfs@xu4    | migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1
apps_nginx-proxy-manager.1.t3v2dwe4msfs@xu4    | [12/16/2019] [10:54:14 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1
apps_nginx-proxy-manager.1.t3v2dwe4msfs@xu4    | [12/16/2019] [10:54:15 PM] [Migrate  ] › ℹ  info      Current database version: none
apps_nginx-proxy-manager.1.t3v2dwe4msfs@xu4    | [12/16/2019] [10:54:15 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...
apps_nginx-proxy-manager.1.t3v2dwe4msfs@xu4    | migration file "20190227065017_settings.js" failed```
