### ISSUE TITLE
Can't renew / request SSL cert from LetsEncrypt

### ISSUE THREAD

**Issue by burnacid** [jc21/nginx-proxy-manager#241]
**Describe the bug**
I keep getting an Internal Server Error when requesting any Lets Encrypt certificates

**To Reproduce**
Certificates > Add Certificate > Lets Encrypt > Fill in any hostname connected > Accept > Hit Save

**Expected behavior**
Expected a certificate to be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/852616/69009613-4bfe8e80-0957-11ea-8470-e1ab4475355d.png)

**Operating System**
Running on QNAP container station.

**Additional context**
I've completly reinstalled the container. No results.

Consoles shows:
```
[11/17/2019] [3:27:23 PM] [Nginx    ] › ℹ  info      Reloading Nginx                                                                                     
[11/17/2019] [3:27:24 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --cert-name "npm-30" --agree-tos --email "xxx@xxx.xxx" --preferred-challenges "dns,http" -n -a webroot -d "cloud.lenders-it.nl"                                                                           
Saving debug log to /var/log/letsencrypt/letsencrypt.log                                                                                                 
Plugins selected: Authenticator webroot, Installer None                                                                                                  
Obtaining a new certificate                                                                                                                              
Performing the following challenges:                                                                                                                     
http-01 challenge for xx.xxxxxx.xx                                                                                                                
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.                                                                       
Waiting for verification...                                                                                                                              
Cleaning up challenges                                                                                                                                   
An unexpected error occurred:                                                                                                                            
The server experienced an internal error :: Error finalizing order                                                                                       
Please see the logfiles in /var/log/letsencrypt for more details.           
```

/var/log/letsencrypt

```
2019-11-17 15:23:07,410:DEBUG:certbot.main:certbot version: 0.28.0
2019-11-17 15:23:07,414:DEBUG:certbot.main:Arguments: ['-n', '--force-renewal', '--disable-hook-validation', '--cert-name', 'npm-29']
2019-11-17 15:23:07,416:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-11-17 15:23:07,445:DEBUG:certbot.log:Root logging level set at 20
2019-11-17 15:23:07,448:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-11-17 15:23:07,451:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.28.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1247, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 389, in handle_renewal_request
    conf_files = [storage.renewal_file_for_certname(config, config.certname)]
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 50, in renewal_file_for_certname
    "{1}).".format(certname, path))
certbot.errors.CertStorageError: No certificate found with name npm-29 (expected /etc/letsencrypt/renewal/npm-29.conf).
```

**Comment by burnacid** [comment]
It suddenly works now. No clue what happened

**Comment by Zibbp** [comment]
Their renew server was having issues yesterday.
