### ISSUE TITLE
I feel stupid, but I have this issue, what's wrong?

### ISSUE THREAD

**Issue by lesu1** [jc21/nginx-proxy-manager#276]
[1/17/2020] [11:37:34 PM] [Global   ] › ✖  error     Config file /app/config/production.json cannot be read Error: Config file /app/config/production.json cannot be read
    at Config.util.parseFile (/app/node_modules/config/lib/config.js:752:11)
    at /app/node_modules/config/lib/config.js:595:28
    at Array.forEach (<anonymous>)
    at /app/node_modules/config/lib/config.js:591:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/app/node_modules/config/lib/config.js:590:13)
    at new Config (/app/node_modules/config/lib/config.js:136:27)
    at Object.<anonymous> (/app/node_modules/config/lib/config.js:1638:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening

**Comment by 1RF17** [comment]
How did you solve this? I have the same problem.

**Comment by lesu1** [comment]
Just remove all images.

Best Regards

________________________________
