### ISSUE TITLE
Add Access List does not work

### ISSUE THREAD

**Issue by xsliii** [jc21/nginx-proxy-manager#299]
I'm using the current version of the nginx-proxy-manager:latest image in my docker setup on my server.

When I want to add a basic authentication "further called access list", I just receiv a "internal error" popup in the manager administration view.

The container log says the following:

[2/20/2020] [11:45:53 PM] [Access   ] › ℹ  info      Building Access file #1 for: chainovate
[2/20/2020] [11:45:54 PM] [Access   ] › ℹ  info      Adding: chris
[2/20/2020] [11:45:54 PM] [Access   ] › ✖  error     Error: Command failed: /usr/bin/htpasswd -b "/data/access/1" "chris" "asdasd123" 
/bin/sh: /usr/bin/htpasswd: not found

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2/20/2020] [11:45:54 PM] [Access   ] › ✖  error     Error: Command failed: /usr/bin/htpasswd -b "/data/access/1" "chris" "asdasd123" 
/bin/sh: /usr/bin/htpasswd: not found

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2/20/2020] [11:45:54 PM] [Access   ] › ✔  success   Built Access file #1 for: chainovate
[2/20/2020] [11:45:54 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/htpasswd -b "/data/access/1" "chris" "asdasd123"
/bin/sh: /usr/bin/htpasswd: not found

It seems that the provided image has no installed "apache2-utils" package.

My Workaround:
using a own Dockerfile extending from the provided nginx-proxy-manager image and install the missing "apache2-utils" package.

**Comment by jc21** [comment]
Ok must have missed that in the new base image. Will fix it

**Comment by xsliii** [comment]
Thanks 👍 could you give me an estimate if possible?

**Comment by jc21** [comment]
In the next 4 hours or so

**Comment by jc21** [comment]
This base image is still building and then NPM needs to be rebuilt with it. Will comment again when this is all done.

**Comment by jc21** [comment]
All done, pull either `latest`, `2` or `2.1.1` docker image tag.

**Comment by xapfer** [comment]
Hello,

I recently installed npm in RPi, using another mariDB package, all seems to work fine but I have the same problem. The ACLs do nothing.

I've checked latest and 2.1.1 packages.

Thank you for your work.

**Comment by SAOPP** [comment]
Guys, can u tell me, I don't understand a bit current logic, for example, there is 1 group, can I add a rule so that it works for any access from any IP - but with basic authentication for the host?

**Comment by SAOPP** [comment]
Oooops... I apologize, it looks like I figured it out, it is just necessary after each change in the ACL, reapply the host settings. Before these actions, it looked as if my changes in the ACL didn't bring any effect. It looks like the question has been cleared, thanks.

**Comment by nashosted** [comment]
I have a video here showing the basics. https://www.youtube.com/watch?v=0CSvMUJEXIw
