### ISSUE TITLE
Can't get DNS cert if using netcup as DNS provider

### ISSUE THREAD

**Issue by Trollwut** [jc21/nginx-proxy-manager#710]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - yes
- Are you sure you're not using someone else's docker image?
  - nope
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
  - it's not really, that's why I need DNS challenge

**Describe the bug**
- version:

So I went so "SSL" in NPM and clicked "Add SSL Certificate".

I'm using DNS-Challenge and selected `netcup` as my DNS Provider.

In the credentials field below, I kept the standard input, but replaced my credentials after the `=` signs.

Then I agree to the TOS and click "Save".

It then needs like 10 seconds and aborts with an error, that all of these credentials haven't been found.

Error from NPM:

```
Error: Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-4" --agree-tos --email "MYMAIL" --domains "MYDOMAIN" --authenticator certbot-dns-netcup:dns-netcup --certbot-dns-netcup:dns-netcup-credentials "/etc/letsencrypt/credentials/credentials-4"
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-dns-netcup:dns-netcup, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for MYDOMAIN
Cleaning up challenges
Missing properties in credentials configuration file /etc/letsencrypt/credentials/credentials-4:
 * Property "certbot_dns_netcup:dns_netcup_customer_id" not found (should be Customer ID associated with netcup account).
 * Property "certbot_dns_netcup:dns_netcup_api_key" not found (should be Key for CCP API, see https://www.netcup-wiki.de/wiki/CCP_API).
 * Property "certbot_dns_netcup:dns_netcup_api_password" not found (should be Password for CCP API, see https://www.netcup-wiki.de/wiki/CCP_API).

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

And this is the `docker-compose logs -f` when pressing "Save":

```
nginx-proxy_1  | [11/10/2020] [12:12:22 PM] [Nginx    ] › ℹ  info      Reloading Nginx
nginx-proxy_1  | [11/10/2020] [12:12:22 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-4" --agree-tos --email "MYMAIL" --domains "MYDOMAIN" --authenticator certbot-dns-netcup:dns-netcup --certbot-dns-netcup:dns-netcup-credentials "/etc/letsencrypt/credentials/credentials-4"
nginx-proxy_1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx-proxy_1  | Plugins selected: Authenticator certbot-dns-netcup:dns-netcup, Installer None
nginx-proxy_1  | Obtaining a new certificate
nginx-proxy_1  | Performing the following challenges:
nginx-proxy_1  | dns-01 challenge for MYDOMAIN
nginx-proxy_1  | Cleaning up challenges
nginx-proxy_1  | Missing properties in credentials configuration file /etc/letsencrypt/credentials/credentials-4:
nginx-proxy_1  |  * Property "certbot_dns_netcup:dns_netcup_customer_id" not found (should be Customer ID associated with netcup account).
nginx-proxy_1  |  * Property "certbot_dns_netcup:dns_netcup_api_key" not found (should be Key for CCP API, see https://www.netcup-wiki.de/wiki/CCP_API).
nginx-proxy_1  |  * Property "certbot_dns_netcup:dns_netcup_api_password" not found (should be Password for CCP API, see https://www.netcup-wiki.de/wiki/CCP_API).
```

Just to be sure: Of course I have normal email adresses and stuff, just don't want to show it publicly here :) 

It seems like this credential file is missing somehow. I don't know if it clears the file on an error run, but even when looking at the volume, or executing bash inside the container, I can't find a file:

```
[root@docker-19942efd9143:/app]# ls -a /etc/letsencrypt/credentials/
.
..
```

**To Reproduce**

I have included all steps into the error description.

**Expected behavior**
Well, getting my SSL certificate, no errur runs.

**Operating System**
- Debian 10 x64, NPM via docker. Everything up-to-date.

**Additional context**
Nothing special. In fact it's a fresh install, installed docker(-compose) and ran NPM. Nothing else on this machine for now.

**Comment by Trollwut** [comment]
I confirmed via `watch ls -la` and `watch cat *` that the given credential file is being created (with correct content) and then deleted after the error occurs. So it doesn't seem like a file-writing problem.

**Comment by Trollwut** [comment]
after an hour of testing, I found out, that the template credentials are "wrong". :) 

as the error says, it awaits `certbot_dns_netcup:dns_netcup_customer_id` and not `dns_netcup_customer_id` for example. So adding this `certbot_dns_netcup:` in front of every line and it tries to do the challange.

---

I now get another error where I'm on it, don't know much to tell about it yet, just adding it here for sake of completness:

```
nginx-proxy_1  | [11/10/2020] [1:29:31 PM] [Nginx    ] › ℹ  info      Reloading Nginx
nginx-proxy_1  | [11/10/2020] [1:29:31 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-10" --agree-tos --email "MYMAIL" --domains "*.MYDOMAIN" --authenticator certbot-dns-netcup:dns-netcup --certbot-dns-netcup:dns-netcup-credentials "/etc/letsencrypt/credentials/credentials-10"
nginx-proxy_1  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx-proxy_1  | Plugins selected: Authenticator certbot-dns-netcup:dns-netcup, Installer None
nginx-proxy_1  | Obtaining a new certificate
nginx-proxy_1  | Performing the following challenges:
nginx-proxy_1  | dns-01 challenge for MYDOMAIN
nginx-proxy_1  | Waiting 10 seconds for DNS changes to propagate
nginx-proxy_1  | Waiting for verification...
nginx-proxy_1  | Challenge failed for domain MYDOMAIN
nginx-proxy_1  | dns-01 challenge for MYDOMAIN
nginx-proxy_1  | Cleaning up challenges
nginx-proxy_1  | Some challenges have failed.
```

**Comment by Trollwut** [comment]
Ok, looking through the `letsencrypt.log it seems like those challenges work, but it ultimately can't find the TXT required for the last challenge.

Can I assume that the TXT is being set (and removed on failure) by the API? Or when do I set which TXT entry?

I can't see anything reminding me about to set the TXT.

**Comment by Trollwut** [comment]
Here I go again, sorry for spam:

I set the propagation time to a whopping 500 seconds and BOOM! it works! :) 

So for future readers:

The credentials have to be set with the correct names, as specified here: https://github.com/jc21/nginx-proxy-manager/issues/710#issuecomment-724703709

I leave this ticket open, even though I solved it for me, so that a maintainer can check if there is something wrong with the credential template for the `netcup` DNS provider. :)
