### ISSUE TITLE
limit_rate, limit_conn

### ISSUE THREAD

**Issue by Nuke142** [jc21/nginx-proxy-manager#780]
I need this lines for my config:
```
limit_conn perip 1;
limit_rate 10240k;
limit_conn perserver 30;
```
When i insert it to
`server {`
then server can't start and shows error:
```
[nginx] starting...
nginx: [emerg] zero size shared memory zone "perip"
[12/18/2020] [11:51:44 AM] [SSL ] › ✖ error Error: Command failed: /usr/sbin/nginx -t

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] zero size shared memory zone "perip"
nginx: configuration file /etc/nginx/nginx.conf test failed


at ChildProcess.exithandler (child_process.js:303:12)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[nginx] starting...
nginx: [emerg] zero size shared memory zone "perip"
[nginx] starting...
nginx: [emerg] zero size shared memory zone "perip"
[nginx] starting...
nginx: [emerg] zero size shared memory zone "perip"
[nginx] starting...
nginx: [emerg] zero size shared memory zone "perip"
[nginx] starting...
nginx: [emerg] zero size shared memory zone "perip"
[nginx] starting...
```

How to user this properly with NPM?

**Comment by thytetgc** [comment]
> I need limit max connection speed for clients and i try this lines for my config:
> 
> ```
> limit_conn perip 1;
> limit_rate 10240k;
> limit_conn perserver 30;
> ```
> 
> When i insert it to
> `server {`
> then server can't start and shows error:
> 
> ```
> [nginx] starting...
> nginx: [emerg] zero size shared memory zone "perip"
> [12/18/2020] [11:51:44 AM] [SSL ] › ✖ error Error: Command failed: /usr/sbin/nginx -t
> 
> nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
> nginx: [emerg] zero size shared memory zone "perip"
> nginx: configuration file /etc/nginx/nginx.conf test failed
> 
> 
> at ChildProcess.exithandler (child_process.js:303:12)
> at ChildProcess.emit (events.js:315:20)
> at maybeClose (internal/child_process.js:1021:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> [nginx] starting...
> nginx: [emerg] zero size shared memory zone "perip"
> [nginx] starting...
> nginx: [emerg] zero size shared memory zone "perip"
> [nginx] starting...
> nginx: [emerg] zero size shared memory zone "perip"
> [nginx] starting...
> nginx: [emerg] zero size shared memory zone "perip"
> [nginx] starting...
> nginx: [emerg] zero size shared memory zone "perip"
> [nginx] starting...
> ```
> 
> How to user this properly with NPM?

limit_rate is working fine!

But connection limit does not work!

It would be very good if there is support for

https://github.com/cfsego/limit_upload_rate

**Comment by chaptergy** [comment]
See https://github.com/jc21/nginx-proxy-manager/issues/116

**Comment by mgutt** [comment]
> limit_rate is working fine!

Does it? I tested the following code, but it has no effect 😢

```
location / {
  # limit download speed
  if ($request_method = GET ) {
    add_header Strict-Transport-Security "max-age=16552000; includeSubdomains; preload;";
    #  only for files bigger than 10MB
    limit_rate_after 10000k;
    # set speed to 10 MBit/s
    limit_rate 1250k;
  }
```

I even tested only `limit_rate 1250k;` outside the location block (= server block), but still no bandwidth limitation while downloading files 🤔
