### ISSUE TITLE
Another instance of Certbot is already running

### ISSUE THREAD

**Issue by cargnellogiacomo** [jc21/nginx-proxy-manager#918]
**Describe the bug**
- I have some SSL certificates generated in NPM via Let's Encrypt that need to be renewed and I receive a message that 'Another instance of Certbot is already running.'
- Nginx Proxy Manager version: 2.8.0

**To Reproduce**
1. Go to 'SSL Certificates'
2. Click on 'Renew Now' for a specific certificate
3. See error:
[2/28/2021] [1:56:54 PM] [SSL      ] › ℹ  info      Renewing Let'sEncrypt certificates for Cert #3: xxxxxx.duckdns.org                                              
[2/28/2021] [1:56:57 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot renew --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-3" --preferred-challenges "dns,http" --disable-hook-validation                                                                                                          
Another instance of Certbot is already running.  
[2/28/2021] [2:01:29 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation

**Expected behavior**
The certificate is renewed without error.

**Operating System**
- NPM latest image (2.8.0) on Docker (QNAP container station)

**Comment by mbenkler** [comment]
i have the same issue with NPM 2.8.0

**Comment by cargnellogiacomo** [comment]
I tried the same. I will see if at the time of the renew I will notice the same issue.

**Comment by henkisdabro** [comment]
I'm experiencing this error on (docker) version 2.8.1 when issuing new letsencrypt cert.

**Comment by jzcad1828** [comment]
I ran into this with v2.8.1 docker image. In my case, I docker exec bash'd the npm app container and killed the existing certbot process. This allowed me to generate a certificate from the CLI and UI. This occurred on an earlier version of NPM from January, and after upgrading it to v2.8.1.

**Comment by samr28** [comment]
Also running into this issue. I docker exec'd in too and there was one running that seemed to be for renewal. Even if I kill that one, it still fails. I also checked and after killing the renewal one, there were no existing lock files for it.

Any other suggestions to fix?

**Comment by cargnellogiacomo** [comment]
> I ran into this with v2.8.1 docker image. In my case, I docker exec bash'd the npm app container and killed the existing certbot process. This allowed me to generate a certificate from the CLI and UI. This occurred on an earlier version of NPM from January, and after upgrading it to v2.8.1.

I cannot test now as NPM does not renew certificates that are not due for renewal. If you restart the container, do you see the same issue and do you need to kill everytime the certbot process?

**Comment by kamegami13** [comment]
I have the same issue. It occurs when I attempt to create a new SSL cert in the SSL tab. If I attempt to renew a certificate or create a new certificate in the proxy host menu then I just get "Internal Error". I have restarted my container numerous times and have attempted to kill existing certbot processes. What occurs is a new certbot process will immediately start. I will even see multiple certbot processes in the ps menu and see different PIDs if I run multiple 'ps' commands in a row. Perhaps cerbot is continually being started by a background process on a loop due to some error that occurs, and thus there is always a lock when a certbot instance is called from the UI manually. The container logs didn't have any useful information, I'm not sure where to find a general log file.

Error: Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-21" --agree-tos --email "natalielwall@gmail.com" --preferred-challenges "dns,http" --domains "bw.abaris.xyz" 
Another instance of Certbot is already running.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by at-cf** [comment]
```
docker exec -it container_name  /bin/bash
ps -ef | grep certb
kill <process id from prev. command>
```
Then new cert can be added. Seems like it was unable to renew the SSL cert (using DNS challenge in my case) and the process that was trying is re-spawned, even on --force-recreate container restart, even after SSL certificate deletion. Also using v2.8.1.

**Comment by kamegami13** [comment]
A followup on this, I noticed certb has a new process id everytime i check. The commands below are run in quick succession, certb seems to be failing/restarting in an endless loop.

```
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
27412 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# kill 27412
bash: kill: (27412) - No such process
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
27897 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
27947 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
27988 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
27990 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
28041 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
28043 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
28045 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
28086 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
28141 root      0:00 grep certb
[root@docker-504864c54ac4:/app]# ps -ef | grep certb
28182 root      0:00 grep certb
[root@docker-504864c54ac4:/app]#
```

**Comment by tarkh** [comment]
> followup

`grep certb` is the process of you doing `grep certb` command at current time, it's not certbot process.

**Comment by chaptergy** [comment]
I am not sure when exactly certbot does this, but there are two things you can do to fix this:  
Kill the second certbot process if it is indeed running as already answered [by others](https://github.com/jc21/nginx-proxy-manager/issues/918#issuecomment-825775554): 
```commandline
ps -ef | grep certb
kill <process id from prev. command>
```

The other possibility is that there isn't actually a second process running, but there is a lockfile left somewhere by certbot, which you can delete by running:
```commandline
find / -type f -name ".certbot.lock" -exec rm {} \;
```
Unfortunately I don't think there is a "fix" to prevent this from occuring except to switch away from certbot, which is planned for [v3](https://github.com/jc21/nginx-proxy-manager/discussions/1202). 

<sub>[Source](https://community.letsencrypt.org/t/solved-another-instance-of-certbot-is-already-running/44690)</sub>

**Comment by eitch** [comment]
I have the same issue, but something that is really weird, is that ps doesn't seem to be installed:

    sudo docker compose exec app bash
    [root@docker-c661c56fc90a:/app]# ps
    bash: ps: command not found

How can this be? What am i missing?

**Comment by eitch** [comment]
After installing procps ps is available. I find it weird that such a tool is missing, but so much other tools are available... Anyhow, i solved my issue. Thanks

**Comment by Cyanoure** [comment]
Same error here. I don't know when did it broke. I pulled the latest version of the image, restarted everything, same error.

**Comment by rombat** [comment]
> Same error here. I don't know when did it broke. I pulled the latest version of the image, restarted everything, same error.
> 
> The following command from @chaptergy is solved the problem and all certs are automatically updated:
> 
> ```shell
> find / -type f -name ".certbot.lock" -exec rm {} \;
> ```
> 
> I think this should be fixed. I don't remember doing anything that could break this.

that did the trick, thanks a lot !
